/**
 * You are given two strings s and t.
 * - String t is generated by random shuffling string s and then add
 *   one more letter at a random position.
 * - Return the letter that was added to t.
 *
 * Time Complexity: O(N)
 * Space Complexity: O(1)
 *
 * #hash-table #strings
 */

function findTheDifference(s: string, t: string): string {
  let accumulator = 0;

  for (const letter of s + t) {
    accumulator ^= letter.charCodeAt(0);
  }

  return String.fromCharCode(accumulator);
}

// function findTheDifference(s: string, t: string): string {
//   const existingLetters: Record<string, number> = {};

//   for (let i = 0; i < s.length; i++) {
//     if (!existingLetters[s[i]]) {
//       existingLetters[s[i]] = 1;
//     } else {
//       existingLetters[s[i]] = existingLetters[s[i]] + 1;
//     }
//   }

//   for (let i = 0; i < t.length; i++) {
//     if (!existingLetters[t[i]]) {
//       return t[i];
//     }

//     existingLetters[t[i]] -= 1;
//     if (existingLetters[t[i]] === 0) {
//       delete existingLetters[t[i]];
//     }
//   }

//   return Object.keys(existingLetters)[0];
// }

//
//

describe('find the difference', () => {
  test('should return `e`', () => {
    const s = 'abcd';
    const t = 'abcde';
    const result = findTheDifference(s, t);
    expect(result).toEqual('e');
  });

  test('should return `y`', () => {
    const s = '';
    const t = 'y';
    const result = findTheDifference(s, t);
    expect(result).toEqual('y');
  });

  test('should return `w`', () => {
    const s = 'hhellowworld';
    const t = 'hhelloworld';
    const result = findTheDifference(s, t);
    expect(result).toEqual('w');
  });
});
